using System.Collections;
using System.Collections.Generic;
//using UnityEditor.Rendering.LookDev;
using UnityEngine;
using UnityEngine.UI;

public class ScreenFader : MonoBehaviour
{
    [Header("<=== Image ===>")]
    [SerializeField] Image fadePanel;

    public float fadeDuration = 1.0f;  // ãƒ•ã‚§ãƒ¼ãƒ‰ã•ã›ã‚‹æ™‚é–“ã‚’è¨­å®šã—ã¦ãã ã•ã„
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public IEnumerator BackBlack()
    {
        fadePanel.gameObject.SetActive(true);
        //fadePanel.enabled = true;                 // ï¿½pï¿½lï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½
        float elapsedTime = 0.0f;                 // ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Color startColor = fadePanel.color;       // ï¿½tï¿½Fï¿½[ï¿½hï¿½pï¿½lï¿½ï¿½ï¿½ÌŠJï¿½nï¿½Fï¿½ï¿½ï¿½æ“¾
        Color endColor = new Color(startColor.r, startColor.g, startColor.b, 1.0f); // ï¿½tï¿½Fï¿½[ï¿½hï¿½pï¿½lï¿½ï¿½ï¿½ÌÅIï¿½Fï¿½ï¿½İ’ï¿½

        // ï¿½tï¿½Fï¿½[ï¿½hï¿½Aï¿½Eï¿½gï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½s
        while (elapsedTime < fadeDuration)
        {
            elapsedTime += Time.deltaTime;                        // ï¿½oï¿½ßï¿½ï¿½Ô‚ğ‘‚â‚·
            float t = Mathf.Clamp01(elapsedTime / fadeDuration);  // ï¿½tï¿½Fï¿½[ï¿½hï¿½Ìiï¿½sï¿½xï¿½ï¿½ï¿½vï¿½Z
            fadePanel.color = Color.Lerp(startColor, endColor, t); // ï¿½pï¿½lï¿½ï¿½ï¿½ÌFï¿½ï¿½ÏXï¿½ï¿½ï¿½Äƒtï¿½Fï¿½[ï¿½hï¿½Aï¿½Eï¿½g
            yield return null;                                     // 1ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ò‹@
        }

        fadePanel.color = endColor;  // ï¿½tï¿½Fï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅIï¿½Fï¿½Éİ’ï¿½
    }
}
